### ISSUE TITLE
`TypeError` at the beginning of an export

### ISSUE THREAD

**Issue by mkasprz** [scastiel/protonmail-export#11]
I experienced quite sad error.
```
Fetching conversations for label 0...
TypeError: Cannot read property 'reduce' of undefined
    at ConversationsFetcher._callee2$ (/usr/local/lib/node_modules/protonmail-export/dist/ConversationFetcher.js:111:69)
    at tryCatch (/usr/local/lib/node_modules/protonmail-export/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:65:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/protonmail-export/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:303:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/protonmail-export/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/usr/local/lib/node_modules/protonmail-export/dist/ConversationFetcher.js:27:191)
    at /usr/local/lib/node_modules/protonmail-export/dist/ConversationFetcher.js:27:361
    at run (/usr/local/lib/node_modules/protonmail-export/node_modules/core-js/modules/es6.promise.js:66:22)
    at /usr/local/lib/node_modules/protonmail-export/node_modules/core-js/modules/es6.promise.js:79:30
    at flush (/usr/local/lib/node_modules/protonmail-export/node_modules/core-js/modules/_microtask.js:18:9)
    at nextTickCallbackWith0Args (node.js:419:9)
```
The version of node.js I have is 4.2.6 if that could change anything.

I hope You could fix it soon. Thank You in advance.

And obviously - thank You for the exporter!

**Comment by mkasprz** [comment]
It's a duplicate of https://github.com/scastiel/protonmail-export/issues/7. I didn't notice it before, sorry.
