### ISSUE TITLE
problem to run the app

### ISSUE THREAD

**Issue by amanda128** [scastiel/protonmail-export#14]
i prepared all of data such as private key and token and session id .
but i dont know waht is the NOTICE-ae3cce(...)=true in your command?
and when i run your command without NOTICE-ae3cce(...)=true then gave me the below error?
please help me dear. thanks
Fetching conversations for label 0...
TypeError: Cannot read property 'reduce' of undefined
    at ConversationsFetcher._callee2$ (AppData\Roaming\npm\node_modules\protonmail-export\dist\ConversationFetcher.js:111:70)
    at tryCatch (AppData\Roaming\npm\node_modules\protonmail-export\node_modules\babel-polyfill\node_modules\regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (AppData\Roaming\npm\node_modules\protonmail-export\node_modules\babel-polyfill\node_modules\regenerator-runtime\runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (AppData\Roaming\npm\node_modules\protonmail-export\node_modules\babel-polyfill\node_modules\regenerator-runtime\runtime.js:117:21)
    at step (\AppData\Roaming\npm\node_modules\protonmail-export\dist\ConversationFetcher.js:27:191)    at \AppData\Roaming\npm\node_modules\protonmail-export\dist\ConversationFetcher.js:27:361
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by vinyll** [comment]
Pretty much the same here:
```
Private key passphrase: *******************************
Fetching conversations for label 0...
TypeError: Cannot read property 'reduce' of undefined
    at ConversationsFetcher._callee2$ (/usr/local/lib/node_modules/protonmail-export/dist/ConversationFetcher.js:111:70)
    at tryCatch (/usr/local/lib/node_modules/protonmail-export/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/protonmail-export/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/protonmail-export/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/usr/local/lib/node_modules/protonmail-export/dist/ConversationFetcher.js:27:191)
    at /usr/local/lib/node_modules/protonmail-export/dist/ConversationFetcher.js:27:361
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
```

Because this is transpiled with babel it is undebuggable for me.

> I also had no clue what the `NOTICE-ae3cce(...)=true` was in the cookie. Didn't appear in mine so I just pasted the cookie value.

@scastiel: is it still working normally for you? Any recommendation if we are misusing?

**Comment by vinyll** [comment]
It looks like [`result.json()`](https://github.com/scastiel/protonmail-export/blob/master/src/ConversationFetcher.js#L33) would return something _falsy_ but there's no `try…catch` here not response status for debugging.
Not sure how to process from here…

**Comment by amanda128** [comment]
please help me step by step to export protonmail.
thanks
