### ISSUE TITLE
TypeError: Cannot read property 'reduce' of undefined

### ISSUE THREAD

**Issue by Kortanul** [scastiel/protonmail-export#7]
getting an error when running on Node 1.7:
```
Private key passphrase: *******************************
Fetching conversations for label 0...
TypeError: Cannot read property 'reduce' of undefined
    at ConversationsFetcher._callee2$ (.nvm/versions/node/v7.0.0/lib/node_modules/protonmail-export/dist/ConversationFetcher.js:111:69)
    at tryCatch (.nvm/versions/node/v7.0.0/lib/node_modules/protonmail-export/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (.nvm/versions/node/v7.0.0/lib/node_modules/protonmail-export/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (.nvm/versions/node/v7.0.0/lib/node_modules/protonmail-export/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (.nvm/versions/node/v7.0.0/lib/node_modules/protonmail-export/dist/ConversationFetcher.js:27:191)
    at .nvm/versions/node/v7.0.0/lib/node_modules/protonmail-export/dist/ConversationFetcher.js:27:361
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by michelfleith** [comment]
Same error Nodejs v6.10.3, Fedora 25

**Comment by michelfleith** [comment]
When add console.log(_context2); line 59 in ConversationFetcher.js  :

An error "Client upgrade required" appear.

```
Context {
  tryEntries: [ { tryLoc: 'root', completion: [Object] } ],
  prev: 0,
  next: 0,
  _sent: undefined,
  sent: undefined,
  done: false,
  delegate: null,
  method: 'next',
  arg: undefined }
Context {
  tryEntries: [ { tryLoc: 'root', completion: [Object] } ],
  prev: 0,
  next: 4,
  _sent: 
   Body {
     url: 'https://mail.protonmail.com/api/conversations/count',
     status: 200,
     statusText: 'OK',
     headers: Headers { _headers: [Object] },
     ok: true,
     body: 
      Gunzip {
        _opts: {},
        _chunkSize: 16384,
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 7,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: true,
        _transformState: [Object],
        _flushFlag: 0,
        _finishFlushFlag: 4,
        _handle: [Object],
        _hadError: false,
        _buffer: <Buffer 48 02 d0 72 83 7f 00 00 48 02 d0 72 83 7f 00 00 40 a2 9f 02 00 00 00 00 40 a2 9f 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ... >,
        _offset: 0,
        _level: -1,
        _strategy: 0,
        _closed: [Getter] },
     bodyUsed: false,
     size: 0,
     timeout: 0,
     _raw: [],
     _abort: false },
  sent: 
   Body {
     url: 'https://mail.protonmail.com/api/conversations/count',
     status: 200,
     statusText: 'OK',
     headers: Headers { _headers: [Object] },
     ok: true,
     body: 
      Gunzip {
        _opts: {},
        _chunkSize: 16384,
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 7,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: true,
        _transformState: [Object],
        _flushFlag: 0,
        _finishFlushFlag: 4,
        _handle: [Object],
        _hadError: false,
        _buffer: <Buffer 48 02 d0 72 83 7f 00 00 48 02 d0 72 83 7f 00 00 40 a2 9f 02 00 00 00 00 40 a2 9f 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ... >,
        _offset: 0,
        _level: -1,
        _strategy: 0,
        _closed: [Getter] },
     bodyUsed: false,
     size: 0,
     timeout: 0,
     _raw: [],
     _abort: false },
  done: false,
  delegate: null,
  method: 'next',
  arg: 
   Body {
     url: 'https://mail.protonmail.com/api/conversations/count',
     status: 200,
     statusText: 'OK',
     headers: Headers { _headers: [Object] },
     ok: true,
     body: 
      Gunzip {
        _opts: {},
        _chunkSize: 16384,
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 7,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: true,
        _transformState: [Object],
        _flushFlag: 0,
        _finishFlushFlag: 4,
        _handle: [Object],
        _hadError: false,
        _buffer: <Buffer 48 02 d0 72 83 7f 00 00 48 02 d0 72 83 7f 00 00 40 a2 9f 02 00 00 00 00 40 a2 9f 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ... >,
        _offset: 0,
        _level: -1,
        _strategy: 0,
        _closed: [Getter] },
     bodyUsed: false,
     size: 0,
     timeout: 0,
     _raw: [],
     _abort: false } }
Context {
  tryEntries: [ { tryLoc: 'root', completion: [Object] } ],
  prev: 4,
  next: 7,
  _sent: 
   { Code: 5003,
     Error: 'Client upgrade required',
     ErrorDescription: '' },
  sent: 
   { Code: 5003,
     Error: 'Client upgrade required',
     ErrorDescription: '' },
  done: false,
  delegate: null,
  method: 'next',
  arg: 
   { Code: 5003,
     Error: 'Client upgrade required',
     ErrorDescription: '' } }
Context {
  tryEntries: [ { tryLoc: 'root', completion: [Object] } ],
  prev: 7,
  next: 'end',
  _sent: 
   { Code: 5003,
     Error: 'Client upgrade required',
     ErrorDescription: '' },
  sent: 
   { Code: 5003,
     Error: 'Client upgrade required',
     ErrorDescription: '' },
  done: false,
  delegate: null,
  method: 'throw',
  arg: 
   TypeError: Cannot read property 'reduce' of undefined
       at ConversationsFetcher._callee2$ (/usr/lib/node_modules/protonmail-export/dist/ConversationFetcher.js:113:69)
       at tryCatch (/usr/lib/node_modules/protonmail-export/node_modules/regenerator-runtime/runtime.js:65:40)
       at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/lib/node_modules/protonmail-export/node_modules/regenerator-runtime/runtime.js:303:22)
       at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/lib/node_modules/protonmail-export/node_modules/regenerator-runtime/runtime.js:117:21)
       at step (/usr/lib/node_modules/protonmail-export/dist/ConversationFetcher.js:27:191)
       at /usr/lib/node_modules/protonmail-export/dist/ConversationFetcher.js:27:361
       at process._tickCallback (internal/process/next_tick.js:109:7),
  t0: [Function],
  t1: {} }
```

**Comment by frontierpsycho** [comment]
I'm getting the same. Any ideas?

**Comment by frontierpsycho** [comment]
I'm guessing because the protonmail-export code says:

`x-pm-appversion: Web_3.5.12`

while the protonmail requests on my browser say

`x-pm-appversion: Web_3.11.4`

I tried simply replacing the value of `x-pm-appversion` with the latest one reported by the client in the browser, and it worked. Try it out!

**Comment by mkasprz** [comment]
It works! Thank You a lot!
@frontierpsycho , maybe You would like to make a pull request out of that? I know it is not that obvious as `x-pm-appversion` seems to change, but it would be great.

**Comment by frontierpsycho** [comment]
I'm not entirely sure what you mean by "it is not that obvious as x-pm-appversion seems to change", but I made a pull request, changing only the appversion in it. I hope I didn't miss anything.
