### ISSUE TITLE
Keep getting "Wrong passphrase" no matter what I do

### ISSUE THREAD

**Issue by effnorwood** [scastiel/protonmail-export#8]
Tried creating a longer and shorter passphrase, tried finding the key with the salt and triple checked the private key. No matter what I do, I get "Wrong passphrase". Thanks!

/privatekey.txt /prot/
Private key passphrase: *************************************************
Wrong passphrase.
Private key passphrase: *************************************************
Wrong passphrase.
Private key passphrase: 
Error: SIGINT
    at ctrlc (/home/gpu/.nvm/versions/node/v7.7.4/lib/node_modules/protonmail-export/node_modules/password-prompt/index.js:46:16)
    at ReadStream.fn (/home/gpu/.nvm/versions/node/v7.7.4/lib/node_modules/protonmail-export/node_modules/password-prompt/index.js:69:20)
    at emitOne (events.js:96:13)
    at ReadStream.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at ReadStream.Readable.push (_stream_readable.js:136:10)
    at TTY.onread (net.js:563:20)
gpu@gpu:$ node --version
v7.7.4
gpu@gpu:$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"

**Comment by effnorwood** [comment]
Found answer in closed, thanks!

**Comment by vinyll** [comment]
Thanks for closing @effnorwood, but sharing your solution would be probably more helpful ;)
